version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: book-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Books
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./data-samples/Books.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./Book Management/LabServiceAPI
    container_name: book-api
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=Books

  client:
    build:
      context: ./Book Management/LabClient
    container_name: book-client
    depends_on:
      - api
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServerURL=http://api/books

volumes:
  dbdata: